"use client";

import { useState, useEffect, useCallback } from "react";
import {
  Copy,
  Download,
  RotateCcw,
  Sparkles,
  Check,
  FileText,
  ChevronDown,
  ChevronUp,
} from "lucide-react";

interface FormData {
  productName: string;
  productType: string;
  targetUsers: string;
  problemStatement: string;
  coreFeatures: string;
  userFlow: string;
  techStack: string;
  successMetrics: string;
}

const STORAGE_KEY = "bestmcpservers-ai-prd-generator-data";

const defaultForm: FormData = {
  productName: "",
  productType: "AI Agent",
  targetUsers: "",
  problemStatement: "",
  coreFeatures: "",
  userFlow: "",
  techStack: "",
  successMetrics: "",
};

const sampleData: FormData = {
  productName: "TaskFlow",
  productType: "SaaS",
  targetUsers:
    "Freelancers and small teams who need simple project management without the complexity of enterprise tools",
  problemStatement:
    "Existing project management tools are either too simple (Trello) or too complex (Jira). Small teams waste hours setting up workflows they don't need.",
  coreFeatures:
    "1. Kanban board with drag-and-drop\n2. Task assignments with due dates\n3. Simple time tracking per task\n4. Weekly email digest of progress\n5. CSV export for reporting",
  userFlow:
    "1. User signs up with email\n2. Creates first project\n3. Adds tasks to Kanban board\n4. Assigns tasks and sets due dates\n5. Tracks time on active tasks\n6. Views weekly progress digest",
  techStack:
    "Frontend: Next.js 14 + Tailwind CSS\nBackend: Next.js API routes\nDatabase: PostgreSQL via Supabase\nAuth: Supabase Auth\nHosting: Vercel",
  successMetrics:
    "1. User completes onboarding in < 2 minutes\n2. Average session duration > 10 minutes\n3. Weekly active user retention > 40%\n4. NPS score > 50",
};

const productTypes = ["AI Agent", "MCP Server", "SaaS", "Marketplace", "CRM", "Chrome Extension", "Mobile App", "Web App"];

export default function AI_PRD_Generator() {
  const [form, setForm] = useState<FormData>(defaultForm);
  const [generated, setGenerated] = useState("");
  const [copied, setCopied] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [activeField, setActiveField] = useState<string | null>(null);

  // Load from LocalStorage on mount
  useEffect(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        const parsed = JSON.parse(saved);
        setForm((prev) => ({ ...prev, ...parsed }));
      }
    } catch {
      // ignore parse errors
    }
  }, []);

  // Save to LocalStorage on change
  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(form));
  }, [form]);

  const updateField = useCallback(
    (field: keyof FormData, value: string) => {
      setForm((prev) => ({ ...prev, [field]: value }));
    },
    []
  );

  const generatePRD = useCallback(() => {
    const prd = `# ${form.productName || "Product Name"} — Product Requirements Document

## Product Overview

- **Product Name:** ${form.productName || "TBD"}
- **Product Type:** ${form.productType}
- **Last Updated:** ${new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    })}

---

## Target Users

${form.targetUsers || "[Define your primary and secondary user personas]"}

---

## Problem Statement

${form.problemStatement || "[Describe the core problem this product solves]"}

---

## Core Features

${form.coreFeatures || "[List the key features in priority order]"}

---

## User Flow

${form.userFlow || "[Describe the primary user journey step by step]"}

---

## Technical Requirements

${form.techStack || "[Specify frontend, backend, database, auth, hosting, and any third-party integrations]"}

---

## Success Metrics

${form.successMetrics || "[Define measurable KPIs and targets]"}

---

## Future Enhancements

- [ ] Feature or improvement 1
- [ ] Feature or improvement 2
- [ ] Feature or improvement 3

---

*Generated by BestMCPServers AI PRD Generator — https://bestmcpservers.com/ai-prd-generator/*
`;
    setGenerated(prd);
    setShowPreview(true);
  }, [form]);

  const copyToClipboard = useCallback(async () => {
    if (!generated) return;
    try {
      await navigator.clipboard.writeText(generated);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const textarea = document.createElement("textarea");
      textarea.value = generated;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [generated]);

  const downloadMarkdown = useCallback(() => {
    if (!generated) return;
    const blob = new Blob([generated], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${(form.productName || "product").toLowerCase().replace(/\s+/g, "-")}-prd.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [generated, form.productName]);

  const clearAll = useCallback(() => {
    if (
      typeof window !== "undefined" &&
      !window.confirm("Clear all fields? This cannot be undone.")
    ) {
      return;
    }
    setForm(defaultForm);
    setGenerated("");
    setShowPreview(false);
    localStorage.removeItem(STORAGE_KEY);
  }, []);

  const loadSample = useCallback(() => {
    setForm(sampleData);
    setGenerated("");
    setShowPreview(false);
  }, []);

  const fields: {
    key: keyof FormData;
    label: string;
    placeholder: string;
    rows: number;
  }[] = [
    {
      key: "productName",
      label: "Product Name",
      placeholder: "e.g., TaskFlow",
      rows: 1,
    },
    {
      key: "targetUsers",
      label: "Target Users",
      placeholder:
        "Who is this product for? Be specific about their role, pain points, and goals.",
      rows: 3,
    },
    {
      key: "problemStatement",
      label: "Problem Statement",
      placeholder:
        "What problem does this product solve? Why does it matter?",
      rows: 3,
    },
    {
      key: "coreFeatures",
      label: "Core Features",
      placeholder:
        "List the key features in priority order. One per line is fine.",
      rows: 4,
    },
    {
      key: "userFlow",
      label: "User Flow",
      placeholder:
        "Describe the primary user journey step by step, from first visit to core action.",
      rows: 4,
    },
    {
      key: "techStack",
      label: "Tech Stack",
      placeholder:
        "Frontend, backend, database, auth, hosting, third-party services...",
      rows: 3,
    },
    {
      key: "successMetrics",
      label: "Success Metrics",
      placeholder:
        "What does success look like? Define measurable KPIs and targets.",
      rows: 3,
    },
  ];

  return (
    <div className="space-y-6">
      {/* Form */}
      <div className="rounded-xl border border-border bg-card p-5 md:p-6">
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-stone-500" />
            <h2 className="text-lg font-semibold text-foreground">
              Product Details
            </h2>
          </div>
          <button
            onClick={loadSample}
            className="inline-flex items-center gap-1.5 text-xs font-medium text-stone-500 hover:text-foreground transition-colors"
          >
            <Sparkles className="h-3.5 w-3.5" />
            Sample Data
          </button>
        </div>

        <div className="space-y-4">
          {/* Product Name */}
          <div>
            <label className="block text-sm font-medium text-foreground mb-1.5">
              Product Name
            </label>
            <input
              type="text"
              value={form.productName}
              onChange={(e) => updateField("productName", e.target.value)}
              placeholder="e.g., TaskFlow"
              className="w-full rounded-lg border border-border bg-background px-3.5 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-stone-300 transition-all"
            />
          </div>

          {/* Product Type */}
          <div>
            <label className="block text-sm font-medium text-foreground mb-1.5">
              Product Type
            </label>
            <div className="flex flex-wrap gap-2">
              {productTypes.map((type) => (
                <button
                  key={type}
                  onClick={() => updateField("productType", type)}
                  className={`rounded-lg px-4 py-2 text-sm font-medium transition-all ${
                    form.productType === type
                      ? "bg-foreground text-primary-foreground"
                      : "border border-border bg-background text-muted-foreground hover:text-foreground hover:border-stone-300"
                  }`}
                >
                  {type}
                </button>
              ))}
            </div>
          </div>

          {/* Other fields */}
          {fields
            .filter((f) => f.key !== "productName")
            .map((field) => (
              <div key={field.key}>
                <button
                  onClick={() =>
                    setActiveField(activeField === field.key ? null : field.key)
                  }
                  className="flex w-full items-center justify-between py-1"
                >
                  <label className="text-sm font-medium text-foreground">
                    {field.label}
                  </label>
                  {field.rows > 2 && (
                    <span className="text-muted-foreground">
                      {activeField === field.key ? (
                        <ChevronUp className="h-4 w-4" />
                      ) : (
                        <ChevronDown className="h-4 w-4" />
                      )}
                    </span>
                  )}
                </button>
                <div
                  className={`overflow-hidden transition-all ${
                    field.rows <= 2 || activeField === field.key
                      ? "max-h-[500px] opacity-100"
                      : "max-h-0 opacity-0"
                  }`}
                >
                  <textarea
                    value={form[field.key]}
                    onChange={(e) => updateField(field.key, e.target.value)}
                    placeholder={field.placeholder}
                    rows={field.rows}
                    className="w-full rounded-lg border border-border bg-background px-3.5 py-2.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-stone-300 transition-all resize-y"
                  />
                </div>
              </div>
            ))}
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap items-center gap-3 mt-6 pt-5 border-t border-border">
          <button
            onClick={generatePRD}
            className="inline-flex items-center gap-2 rounded-lg bg-foreground px-5 py-2.5 text-sm font-medium text-primary-foreground hover:bg-foreground/90 transition-colors"
          >
            <Sparkles className="h-4 w-4" />
            Generate PRD
          </button>
          <button
            onClick={clearAll}
            className="inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2.5 text-sm font-medium text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
          >
            <RotateCcw className="h-4 w-4" />
            Clear
          </button>
        </div>
      </div>

      {/* Preview */}
      {showPreview && generated && (
        <div className="rounded-xl border border-border bg-card overflow-hidden">
          <div className="flex items-center justify-between px-5 py-3 border-b border-border bg-muted/30">
            <div className="flex items-center gap-2">
              <FileText className="h-4 w-4 text-stone-500" />
              <span className="text-sm font-semibold text-foreground">
                Generated PRD
              </span>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={copyToClipboard}
                className="inline-flex items-center gap-1.5 rounded-lg border border-border px-3 py-1.5 text-xs font-medium text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
              >
                {copied ? (
                  <>
                    <Check className="h-3.5 w-3.5 text-green-600" />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy className="h-3.5 w-3.5" />
                    Copy
                  </>
                )}
              </button>
              <button
                onClick={downloadMarkdown}
                className="inline-flex items-center gap-1.5 rounded-lg border border-border px-3 py-1.5 text-xs font-medium text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
              >
                <Download className="h-3.5 w-3.5" />
                Download .md
              </button>
            </div>
          </div>
          <div className="p-5 overflow-x-auto">
            <pre className="text-sm text-foreground whitespace-pre-wrap font-mono leading-relaxed">
              {generated}
            </pre>
          </div>
        </div>
      )}
    </div>
  );
}
